### ISSUE TITLE
Can't handle ratios with decimals places correctly

### ISSUE THREAD

**Issue by deckchairlabs** [arccoza/postcss-aspect-ratio#3]
When trying to create an aspect ratio of '2.414:1' the css output becomes broken. For reference [https://en.wikipedia.org/wiki/Silver_ratio](https://en.wikipedia.org/wiki/Silver_ratio)

```
.aspect-ratio-silver:before {
    position: relative;
    display: block;
    content: "";
    padding-top: '2.0.24154589371980675%; box-sizing: border-box;
}
```

Note the incorrect percentage value.

**Comment by arccoza** [comment]
Fixed and published to NPM.

**Comment by deckchairlabs** [comment]
Excellent! Thanks

**Comment by arccoza** [comment]
Nw.
