### ISSUE TITLE
generate redundant code

### ISSUE THREAD

**Issue by airen** [arccoza/postcss-aspect-ratio#5]
The compiled CSS will generate redundant code. eg:

```
// Input
[aspectratio] {
  position: relative;
}

[aspectratio]::before {
  content: '';
  display: block;
  width: 1px;
  margin-left: -1px;
  height: 0;
}
[aspectratio][aspect-ratio="16:9"]{
  aspect-ratio: '16:9';
}
[aspectratio][aspect-ratio="4:3"]{
  aspect-ratio: '4:3';
}
```

I want output code like this:

```
// Output
[aspectratio] {
  position: relative;
}
[aspectratio]::before {
  content: '';
  display: block;
  width: 1px;
  margin-left: -1px;
  height: 0;
}
[aspectratio][aspect-ratio="16:9"]{
  padding-top: 56.25%;
}
[aspectratio][aspect-ratio="4:3"]{
  padding-top: 75%;
}
```
But now,the compiled CSS will generate redundant code:

```
[aspectratio] {
    position: relative;
}

[aspectratio]::before {
    content: '';
    display: block;
    width: 1px;
    margin-left: -1px;
    height: 0;
}

[aspectratio][aspect-ratio="16:9"]{
  position: relative;
  box-sizing: border-box;
}

[aspectratio][aspect-ratio="16:9"] > * {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  box-sizing: border-box;
}

[aspectratio][aspect-ratio="16:9"]:before {
  position: relative;
  display: block;
  content: "";
  padding-top: 56.25%;
  box-sizing: border-box;
}
[aspectratio][aspect-ratio="4:3"]{
  position: relative;
  box-sizing: border-box;
}
[aspectratio][aspect-ratio="4:3"] > * {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  box-sizing: border-box;
}
[aspectratio][aspect-ratio="4:3"]:before {
  position: relative;
  display: block;
  content: "";
  padding-top: 75%;
  box-sizing: border-box;
}
```

There is no better way to compile code that is not redundant code？

THX!

**Comment by arccoza** [comment]
The code is not redundant, you've misunderstood how the plugin and the aspect-ratio padding trick works.

The trick relies on a percentage `padding-top` or `padding-bottom`.
The padding will be calculated based on the width of the **parent**; this is why we apply the percentage padding to a pseudo element, so it will force its parent's height to a percentage of its own width.
So an element with `width: 120px` and pseudo element with `padding-top: 10%;` will have a height of `12px`.

The child content `> *` is an absolutely positioned layer stretched over the parent, so we don't upset the ratio.

[A more detailed explanation](http://www.mademyday.de/css-height-equals-width-with-pure-css.html)

There are other variations on this technique, but they all make use of % padding.

**Comment by airen** [comment]
@arccoza Thanks! I know aspect-ratio how to work. I mean, is the compiled code a little more concise. For example, I have a lot of containers, they need aspect ratio. eg：`box1`、`box2` and `box3`. Even if they have the same class name `box`：

```
<div class="box box1">
    <div class="content"></div>
</div>
<div class="box box2">
    <div class="content"></div>
</div>
<div class="box box3">
    <div class="content"></div>
</div>
```

I need the `16/9` for `box1`；the `4/3` for `box2` and the `2/1` for `box3`：

```
// Input
.box1 {
  aspect-ratio: '16:9';
}
.box2 {
  aspect-ratio: '4:3';
}
.box3 {
  aspect-ratio: '2:1';
}
```
the plugin compile: 

```
.box1 {
  position: relative;
  box-sizing: border-box;
}

.box1 > * {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  box-sizing: border-box;
}

.box1:before {
  position: relative;
  display: block;
  content: "";
  padding-top: 56.25%;
  box-sizing: border-box;
}
.box2 {
  position: relative;
  box-sizing: border-box;
}
.box2 > * {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  box-sizing: border-box;
}
.box2:before {
  position: relative;
  display: block;
  content: "";
  padding-top: 75%;
  box-sizing: border-box;
}
.box3 {
  position: relative;
  box-sizing: border-box;
}
.box3 > * {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  box-sizing: border-box;
}
.box3:before {
  position: relative;
  display: block;
  content: "";
  padding-top: 50%;
  box-sizing: border-box;
}
```

Now, the `box1` 、`box2` and `box3` have same code:

```
.box1 {
  position: relative;
  box-sizing: border-box;
}
.box2 {
  position: relative;
  box-sizing: border-box;
}
.box3 {
  position: relative;
  box-sizing: border-box;
}
.box1 > * {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  box-sizing: border-box;
}
.box2 > * {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  box-sizing: border-box;
}
.box3 > * {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  box-sizing: border-box;
}
.box2:before {
  position: relative;
  display: block;
  content: "";
  box-sizing: border-box;
}
.box3:before {
  position: relative;
  display: block;
  content: "";
  box-sizing: border-box;
}
.box1:before {
  position: relative;
  display: block;
  content: "";
  box-sizing: border-box;
}
```
They differ only in the `padding-top` of the pseudo-elements. They have a lot of the same code, a lot of repetition. There is no way for the plug-in to give the same code to a class name, just using `padding-top` on a pseudo-element of a different container. Like this:

```
.box {
  position: relative;
  box-sizing: border-box;
}
.box > * {
  position: relative;
  display: block;
  content: "";
  box-sizing: border-box;
}
.box:before {
  position: relative;
  display: block;
  content: "";
  box-sizing: border-box;
}
```
The different code:

```
.box1:before {
   padding-top: 56.25%;
}
.box2:before {
   padding-top: 75%;
}
.box:before{
  padding-top:50%;
}
```

I wonder if you know what I mean. Is there a better way? Use this plugin. THX!

**Comment by dbox** [comment]
It actually doesn't matter once you use gzip

**Comment by arccoza** [comment]
@dbox is right, with minification and gzip, this isn't really a problem unless you have dozens of different ratios you're using.

I understand what you're trying to do, but unfortunately it's not possible with the current state of the plugin, it was designed to be simple to use, if you want more control you will have to do it manually.

A suggestion:

```css
.box1, .box2, .box3 {
  aspect-ratio: '16:9';
}

.box2:before {
  padding-top: 75%;
}

.box3:before {
  padding-top: 50%;
}
```

This question has given me some ideas for future updates though, perhaps a `ratio(16:9)` function you can use as a value anywhere.
